### ISSUE TITLE
App is compatible with splunk cloud for a SH. Can it update the SHC and the indexers?

### ISSUE THREAD

**Issue by sumang99** [CrossRealms/Splunk-App-Auto-Update-MaxMind-Database#30]
Thanks for the great app but can you provide more details how we can use this in a clustered environment. It's not just my request but several other enterprises are looking for a solution like that. Appreciate any help!

**Comment by sumang99** [comment]
Sorry, I've posted a question before going thru your Notes. As per your comments this works for splunk cloud on a standalone SH/IDM which download the mmdb file and distributes to other instance in a Stack SHC/ES/IDM/SH depending on the stack members. But this app doesn't work when we're in Classic Experience because the deployment design is different. Correct?

**Comment by VatsalJagani** [comment]
@sumang99 - The short answer is, from Splunk version 9.x it should support SHC and Indexer Cluster both, just by configuring on one SH. And same is true for the Cloud Victoria experience.
Due to limitations in Classic Experience, it is not supported in the same way, so the App has dropped support for Classic experience.

**Comment by VatsalJagani** [comment]
As per my comment above, it already supports Victoria Splunk cloud stack with the latest version, so closing this issue.
